# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Utility functions for training with frames dataset

import torch
from typing import Any, Dict, List


def collate_fn_frames(
    batch: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """Collate function for FramesDataset samples that have been preprocessed by VLA preprocessor.

    Args:
        batch: List of samples from FramesDataset with preprocessed tokenized_data

    Returns:
        Dictionary with collated tensors ready for model input
    """
    # Filter out None samples
    batch = [sample for sample in batch if sample is not None]
    if len(batch) == 0:
        raise ValueError("All samples in batch are None")

    # All samples should have tokenized_data (generated by vla_preprocess_func)
    # The tokenized_data already contains all necessary fields like:
    # text, input_ids, attention_mask, pixel_values, image_grid_thw, etc.
    
    output = {}
    
    # Handle trajectory data - concatenate across batch dimension
    ego_xyz_list = []
    ego_rot_list = []
    
    for sample in batch:
        ego_xyz_list.append(sample["ego_history_xyz"])
        ego_rot_list.append(sample["ego_history_rot"])
    
    output["ego_history_xyz"] = torch.cat(ego_xyz_list, dim=0)
    output["ego_history_rot"] = torch.cat(ego_rot_list, dim=0)
    
    # Handle tokenized data
    # Basic collation: concatenate tensors with matching dimension
    if batch[0].get("tokenized_data") is not None:
        tokenized_data = {}
        
        # Get all keys from first sample
        for key in batch[0]["tokenized_data"].keys():
            values = [sample["tokenized_data"][key] for sample in batch]
            
            if isinstance(values[0], torch.Tensor):
                # Concatenate tensors
                tokenized_data[key] = torch.cat(values, dim=0)
            elif isinstance(values[0], str):
                # Keep text as list
                tokenized_data[key] = values
            elif isinstance(values[0], list):
                # Concatenate lists
                tokenized_data[key] = [item for sublist in values for item in sublist]
            else:
                # For other types, just keep the values
                tokenized_data[key] = values
        
        output["tokenized_data"] = tokenized_data
    
    return output
